#!/usr/bin/env python
#
# Turn Kepco power OFF
# J. Kelley, jkelley@icecube.wisc.edu
#

import sys
import time
from kepco import Kepco

HOSTNAME = "drts-pwr1"

k = Kepco(HOSTNAME)
k.off()
if k.isOn():
    print("ERROR: power supply output is still ON!")
    print("Voltage: %.1f V" % k.getVoltage())
    print("Current: %.3f A" % k.getCurrent())
else:
    print("Power supply output is OFF.")

