#!/usr/bin/python
#
# Turn Kepco power OFF
# J. Kelley, jkelley@icecube.wisc.edu
#

import sys
import time
from kepco import Kepco, KepcoException

HOSTNAME = "drts-pwr1"
PORT = 5025

try:
    k = Kepco(HOSTNAME, PORT)
except ConnectionRefusedError:
    print("Couldn't connect to %s:%d, exiting." % (HOSTNAME, PORT))
    sys.exit(-1)
except KepcoException:
    print("Unexpected response from power supply at %s:%d, exiting." % (HOSTNAME, PORT))
    sys.exit(-1)

k.off()
if k.isOn():
    print("ERROR: power supply output is still ON!")
    print("Voltage: %.1f V" % k.getVoltage())
    print("Current: %.3f A" % k.getCurrent())
else:
    print("Power supply output is OFF.")

