#!/usr/bin/python
#
# Turn Keysight power OFF
# J. Kelley, jkelley@icecube.wisc.edu
#

from keysight import Keysight

HOSTNAME = "spwr01"
PORT = 5024

k = Keysight(HOSTNAME, PORT)
k.off()
if k.isOn():
    print "Power supply output is still ON!"
    print "Voltage: %.1f V" % k.getVoltage()
    print "Current: %.3f A" % k.getCurrent()
else:
    print "Power supply output is OFF."

