#!/usr/bin/env python
#
# Turn Kepco power ON
# J. Kelley, jkelley@icecube.wisc.edu
#

import sys
import time
from kepco import Kepco

# Just in case someone is using Python2
try:
    q_input = raw_input
except NameError:
    q_input = input

HOSTNAME = "drts-pwr1"
k = Kepco(HOSTNAME)

if k.isOn():
    print("Power supply output is already ON.")
    sys.exit()
else:
    sys.stdout.write("Turning power supply output ON -- are you sure (y/n)? ")
    choice = q_input().lower()
    if choice in ['yes', 'y']:
        k.on()
    else:
        print("Aborted.")
        sys.exit()

if k.isOn():
    print("Power supply output is ON.")
    time.sleep(2)
    print("Voltage: %.1f V" % k.getVoltage())
    print("Current: %.3f A" % k.getCurrent())
else:
    print("Power supply output is still OFF!")

