#!/usr/bin/python
#
# Turn Keysight scintillator power ON
# J. Kelley, jkelley@icecube.wisc.edu
#

import sys
import time
from keysight import Keysight

HOSTNAME = "spwr01"
PORT = 5024

k = Keysight(HOSTNAME, PORT)
if k.isOn():
    print "Power supply output is already ON."
    sys.exit()
else:
    sys.stdout.write("Turning power supply output ON -- are you sure (y/n)? ")
    choice = raw_input().lower()
    if choice in ['yes', 'y']:
        k.on()
    else:
        print "Aborted."
        sys.exit()

if k.isOn():
    print "Power supply output is ON."
    time.sleep(2)
    print "Voltage: %.1f V" % k.getVoltage()
    print "Current: %.3f A" % k.getCurrent()
else:
    print "Power supply output is still OFF!"

