#!/usr/bin/env python
#
# Get Kepco power supply status
#

import sys
from kepco import Kepco, KepcoException

HOSTNAME = "drts-pwr1"
PORT = 5025

try:
    k = Kepco(HOSTNAME, PORT)
except ConnectionRefusedError:
    print("Couldn't connect to %s:%d, exiting." % (HOSTNAME, PORT))
    sys.exit(-1)
except KepcoException:
    print("Unexpected response from power supply at %s:%d, exiting." % (HOSTNAME, PORT))
    sys.exit(-1)

if k.isOn():
    print("Power supply output is ON.")
    print("Voltage: %.1f V" % k.getVoltage())
    print("Current: %.3f A" % k.getCurrent())
else:
    print("Power supply output is OFF.")
