#!/usr/bin/env python
#
# Get Kepco power supply status
#

import sys
from kepco import Kepco

HOSTNAME = "drts-pwr1"
k = Kepco(HOSTNAME)
print(k)

if k.isOn():
    print("Power supply output is ON.")
    print("Voltage: %.1f V" % k.getVoltage())
    print("Current: %.3f A" % k.getCurrent())
else:
    print("Power supply output is OFF.")
