#!/usr/bin/python
#
# Report Keysight power status
# J. Kelley, jkelley@icecube.wisc.edu
#
import sys
import time
from keysight import Keysight

HOSTNAME = "spwr01"
PORT = 5024

if len(sys.argv) != 2:
   print "Usage: %s <voltage>" % sys.argv[0]
   sys.exit(0)

try:
   v = float(sys.argv[1])
except ValueError:
   print "Error: bad voltage specified, exiting."
   sys.exit(-1)

if (v < 0) or (v > 600):
   print "Error: voltage out of range, exiting."
   sys.exit(-1)

k = Keysight(HOSTNAME, PORT)
print "Setting voltage to %.1f V." % v
k.setVoltage(v)
time.sleep(1)
print "Voltage level: %.1f V" % k.getVoltage()
