#!/usr/bin/env python
#
# Set output voltage
#

import sys
import time
from kepco import Kepco

HOSTNAME = "drts-pwr1"

try:
   v = float(sys.argv[1])
except IndexError:
    print("Usage: %s <voltage>" % sys.argv[0])
    sys.exit()
except ValueError:
    print("Bad voltage specified, exiting.")
    sys.exit(-1)

k = Kepco(HOSTNAME)

if (v < 0) or (v > k.MAX_VOLTAGE):
    print("Voltage out of range, exiting.")
    sys.exit(-1)

print("Setting voltage to %.1f V." % v)
k.setVoltage(v)
time.sleep(1)
if k.isOn():
    print("Voltage level: %.1f V" % k.getVoltage())
else:
    print("Power supply output is OFF.")

